/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SecureResumeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeHR"
      | "calculateSkillScore"
      | "evaluateSkillMatch"
      | "getResumeInfo"
      | "getSkillLevels"
      | "getStats"
      | "hasResume"
      | "hrAddresses"
      | "protocolId"
      | "revokeHR"
      | "submitResume"
      | "updateResume"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "HRAuthorized"
      | "HRRevoked"
      | "ResumeSubmitted"
      | "ResumeUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeHR",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateSkillScore",
    values: [AddressLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "evaluateSkillMatch",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getResumeInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSkillLevels",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getStats", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "hasResume",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hrAddresses",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeHR",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitResume",
    values: [string, string, string, string[], BytesLike[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateResume",
    values: [string, string, string, string[], BytesLike[], BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeHR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateSkillScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evaluateSkillMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResumeInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSkillLevels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasResume", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hrAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revokeHR", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitResume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateResume",
    data: BytesLike
  ): Result;
}

export namespace HRAuthorizedEvent {
  export type InputTuple = [hr: AddressLike];
  export type OutputTuple = [hr: string];
  export interface OutputObject {
    hr: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HRRevokedEvent {
  export type InputTuple = [hr: AddressLike];
  export type OutputTuple = [hr: string];
  export interface OutputObject {
    hr: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResumeSubmittedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResumeUpdatedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SecureResume extends BaseContract {
  connect(runner?: ContractRunner | null): SecureResume;
  waitForDeployment(): Promise<this>;

  interface: SecureResumeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeHR: TypedContractMethod<[hr: AddressLike], [void], "nonpayable">;

  calculateSkillScore: TypedContractMethod<
    [candidate: AddressLike, skillIndices: BigNumberish[]],
    [string],
    "nonpayable"
  >;

  evaluateSkillMatch: TypedContractMethod<
    [candidate: AddressLike, skillIndex: BigNumberish],
    [string],
    "nonpayable"
  >;

  getResumeInfo: TypedContractMethod<
    [user: AddressLike],
    [
      [string, string, string, string[], bigint, bigint] & {
        name: string;
        education: string;
        workExperience: string;
        skillNames: string[];
        createdAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;

  getSkillLevels: TypedContractMethod<[user: AddressLike], [string[]], "view">;

  getStats: TypedContractMethod<[], [bigint], "view">;

  hasResume: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  hrAddresses: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  revokeHR: TypedContractMethod<[hr: AddressLike], [void], "nonpayable">;

  submitResume: TypedContractMethod<
    [
      name: string,
      education: string,
      workExperience: string,
      skillNames: string[],
      skillLevelsExt: BytesLike[],
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  updateResume: TypedContractMethod<
    [
      name: string,
      education: string,
      workExperience: string,
      skillNames: string[],
      skillLevelsExt: BytesLike[],
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeHR"
  ): TypedContractMethod<[hr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "calculateSkillScore"
  ): TypedContractMethod<
    [candidate: AddressLike, skillIndices: BigNumberish[]],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "evaluateSkillMatch"
  ): TypedContractMethod<
    [candidate: AddressLike, skillIndex: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getResumeInfo"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [string, string, string, string[], bigint, bigint] & {
        name: string;
        education: string;
        workExperience: string;
        skillNames: string[];
        createdAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSkillLevels"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasResume"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hrAddresses"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "revokeHR"
  ): TypedContractMethod<[hr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitResume"
  ): TypedContractMethod<
    [
      name: string,
      education: string,
      workExperience: string,
      skillNames: string[],
      skillLevelsExt: BytesLike[],
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateResume"
  ): TypedContractMethod<
    [
      name: string,
      education: string,
      workExperience: string,
      skillNames: string[],
      skillLevelsExt: BytesLike[],
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "HRAuthorized"
  ): TypedContractEvent<
    HRAuthorizedEvent.InputTuple,
    HRAuthorizedEvent.OutputTuple,
    HRAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "HRRevoked"
  ): TypedContractEvent<
    HRRevokedEvent.InputTuple,
    HRRevokedEvent.OutputTuple,
    HRRevokedEvent.OutputObject
  >;
  getEvent(
    key: "ResumeSubmitted"
  ): TypedContractEvent<
    ResumeSubmittedEvent.InputTuple,
    ResumeSubmittedEvent.OutputTuple,
    ResumeSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ResumeUpdated"
  ): TypedContractEvent<
    ResumeUpdatedEvent.InputTuple,
    ResumeUpdatedEvent.OutputTuple,
    ResumeUpdatedEvent.OutputObject
  >;

  filters: {
    "HRAuthorized(address)": TypedContractEvent<
      HRAuthorizedEvent.InputTuple,
      HRAuthorizedEvent.OutputTuple,
      HRAuthorizedEvent.OutputObject
    >;
    HRAuthorized: TypedContractEvent<
      HRAuthorizedEvent.InputTuple,
      HRAuthorizedEvent.OutputTuple,
      HRAuthorizedEvent.OutputObject
    >;

    "HRRevoked(address)": TypedContractEvent<
      HRRevokedEvent.InputTuple,
      HRRevokedEvent.OutputTuple,
      HRRevokedEvent.OutputObject
    >;
    HRRevoked: TypedContractEvent<
      HRRevokedEvent.InputTuple,
      HRRevokedEvent.OutputTuple,
      HRRevokedEvent.OutputObject
    >;

    "ResumeSubmitted(address)": TypedContractEvent<
      ResumeSubmittedEvent.InputTuple,
      ResumeSubmittedEvent.OutputTuple,
      ResumeSubmittedEvent.OutputObject
    >;
    ResumeSubmitted: TypedContractEvent<
      ResumeSubmittedEvent.InputTuple,
      ResumeSubmittedEvent.OutputTuple,
      ResumeSubmittedEvent.OutputObject
    >;

    "ResumeUpdated(address)": TypedContractEvent<
      ResumeUpdatedEvent.InputTuple,
      ResumeUpdatedEvent.OutputTuple,
      ResumeUpdatedEvent.OutputObject
    >;
    ResumeUpdated: TypedContractEvent<
      ResumeUpdatedEvent.InputTuple,
      ResumeUpdatedEvent.OutputTuple,
      ResumeUpdatedEvent.OutputObject
    >;
  };
}
